# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAdmin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_admin(self):
    self.driver.get("http://127.0.0.1:8000/admin/login/?next=/admin/")
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("root")
    self.driver.find_element(By.CSS_SELECTOR, ".login").click()
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("root")
    self.driver.find_element(By.CSS_SELECTOR, ".submit-row > input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".model-articles .addlink").click()
    self.driver.find_element(By.ID, "id_title").send_keys("qwe")
    self.driver.find_element(By.ID, "id_post").click()
    self.driver.find_element(By.ID, "id_post").send_keys("qweqwe")
    self.driver.find_element(By.CSS_SELECTOR, ".date-icon").click()
    self.driver.find_element(By.LINK_TEXT, "9").click()
    self.driver.find_element(By.CSS_SELECTOR, ".clock-icon").click()
    self.driver.find_element(By.LINK_TEXT, "Midnight").click()
    self.driver.find_element(By.NAME, "_save").click()
    self.driver.find_element(By.LINK_TEXT, "News").click()
    self.driver.find_element(By.LINK_TEXT, "Articless").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4)").click()
    self.driver.set_window_size(1315, 837)
  
